// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scaffolding_inverso.Data;

#nullable disable

namespace Scaffolding_inverso.Data.Migrations
{
    [DbContext(typeof(HeroesContext))]
    [Migration("20260918115443_InitialHeroes")]
    partial class InitialHeroes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Scaffolding_inverso.Models.Heroes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentidadSecreta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Scaffolding_inverso.Models.SuperPoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroeId");

                    b.ToTable("SuperPoderes");
                });

            modelBuilder.Entity("Scaffolding_inverso.Models.SuperPoderes", b =>
                {
                    b.HasOne("Scaffolding_inverso.Models.Heroes", "Heroe")
                        .WithMany("SuperPoderes")
                        .HasForeignKey("HeroeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroe");
                });

            modelBuilder.Entity("Scaffolding_inverso.Models.Heroes", b =>
                {
                    b.Navigation("SuperPoderes");
                });
#pragma warning restore 612, 618
        }
    }
}
